### ISSUE TITLE
semi-colon escape

### ISSUE THREAD

**Issue by cookednoodles** [jorgebastida/django-dajaxice#7] opened 2010-03-19 17:40 UTC
Any text sent via ajax that contains a ; will produce an error.

**Comment by jorgebastida** [comment] 2010-03-20 09:20
Sorry, but i can't reproduce your problem. Please, share more info about django and dajaxice version ,  browser etc...
Thanks a lot.

**Comment by cookednoodles** [comment] 2010-03-20 10:22
I have the same problem using chrome and firefox and can reproduce it by going to :
http://dajaxproject.com/dajaxice_args/

I can post the message fine and get a response, however as soon as the text box contains a ; for example "Some ;text..." there won't be a reply.

In the runserver :
ERROR:root:DAJAXICE argv exception Unterminated string starting at: line 1 column 8 (char 8)  
ERROR:root:DAJAXICE Exception functionname() takes exactly 2 arguments (1 given)                             

[...]

Traceback (most recent call last):
  File "/usr/local/lib/python2.6/site-packages/dajaxice/core/DajaxiceRequest.py", line 216, in process
    response = '%s(%s)' % ( callback, thefunction(self.request, **argv) )  
TypeError: functionname() takes exactly 2 arguments (1 given)

However if you remove the ; there is no such error and it works fine.

**Comment by jorgebastida** [comment] 2010-03-20 10:55
Ok, i reproduce the problem. It seems that some characters like ; breaks the request payload. The first workaround is to scape() the json data at dajaxice.core.js (16).

send_data.push('argv='+escape(JSON.stringify(argv)));

It works for me

**Comment by jorgebastida** [comment] 2010-03-28 21:04
Fixed in 0.1.3

**Closed as completed by jorgebastida** 2010-03-28 21:04 UTC
Labels: acepted, 0.1.3
